notifications:
  email: false
jobs:
  include:
    - stage: Test
      language: go
      go:
        - '1.10'
      install:
        - go get -u github.com/kardianos/govendor
        - govendor sync
      script: go test
    - stage: Build Docker Image
      sudo: required
      services:
        - docker
      script:
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker build -f Dockerfile -t communityannouncer/announcer-service .
        - docker push communityannouncer/announcer-service
    - stage: Deploy to Staging
      sudo: required
      services:
        - docker
      script:
        - docker pull communityannouncer/announcer-service
        - docker tag communityannouncer/announcer-service registry.heroku.com/community-announcer-staging/web
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
        - docker push registry.heroku.com/community-announcer-staging/web
    - stage: Integration Test
      sudo: required
      services:
        - docker
      script: docker run -it --rm -v $(pwd)/blueprints:/blueprints --entrypoint dredd burakince/docker-dredd /blueprints/*.md https://community-announcer-staging.herokuapp.com
    - stage: Deploy to Production
      sudo: required
      services:
        - docker
      script:
        - docker pull communityannouncer/announcer-service
        - docker tag communityannouncer/announcer-service registry.heroku.com/community-announcer/web
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
        - docker push registry.heroku.com/community-announcer/web
