language: go
go:
- '1.10'
sudo: required
services:
- docker
install:
- go get -u github.com/kardianos/govendor
- govendor sync
jobs:
  include:
    - stage: test
      script: go test
    - stage: deploy
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
    - script: docker build -f Dockerfile -t registry.heroku.com/community-announcer/web .
    - script: docker push registry.heroku.com/community-announcer/web
